# Generated by Django 5.2.1 on 2025-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
